// DUBIS - Product Catalog
// Auto-generated by sync-products — DO NOT EDIT MANUALLY
// Last sync: 2026-04-23 — Honey Brown removed (5 products), aligned with stock
// Collection 01 - For the rest of us

const SIZES_TSHIRT    = ['S', 'M', 'L', 'XL', '2XL', '3XL'];
const SIZES_HOODIE    = ['S', 'M', 'L', 'XL', '2XL', '3XL'];
const SIZES_LONGSLEEVE = ['S', 'M', 'L', 'XL', '2XL', '3XL'];
const SIZES_CAP       = ['One Size'];

const SIZE_GUIDE_TSHIRT = [
    { size: 'S',   chest: 46, length: 70 },
    { size: 'M',   chest: 51, length: 72 },
    { size: 'L',   chest: 56, length: 74 },
    { size: 'XL',  chest: 61, length: 76 },
    { size: '2XL', chest: 66, length: 78 },
    { size: '3XL', chest: 71, length: 80 },
];

const SIZE_GUIDE_HOODIE = [
    { size: 'S',   chest: 56, length: 67 },
    { size: 'M',   chest: 61, length: 70 },
    { size: 'L',   chest: 66, length: 73 },
    { size: 'XL',  chest: 71, length: 76 },
    { size: '2XL', chest: 76, length: 79 },
    { size: '3XL', chest: 81, length: 82 },
];

const SIZE_GUIDE_LONGSLEEVE = SIZE_GUIDE_TSHIRT;

const CARE_TSHIRT = [
    "Machine wash cold, inside out",
    "Tumble dry low heat",
    "Do not bleach",
    "Do not iron directly on print",
    "Do not dry clean"
];

const CARE_HOODIE = [
    "Machine wash cold, inside out",
    "Tumble dry low heat",
    "Do not bleach",
    "Do not iron directly on print",
    "Do not dry clean"
];

const CARE_TSHIRT_HE = [
    "כביסה קרה במכונה, בפנים החוצה",
    "ייבוש בחום נמוך",
    "אין להלבין",
    "אל תגהץ ישירות על ההדפסה",
    "אין לניקוי יבש"
];

const CARE_HOODIE_HE = CARE_TSHIRT_HE;

const CARE_CAP_HE = [
    "ניקוי ידני בלבד",
    "אין כביסה במכונה",
    "אין לייבש במייבש",
    "עצב מחדש וייבש באוויר"
];

const products = [

    // ─── UNISEX ────────────────────

    {
        id: 1,
        phrase: "I'm not fat, I'm a limited edition",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "unisex",
        price: 14,
        image: "images/product-1.jpg",
        colors: ["Black","White","Cream","Navy","Red"],
        sizes: SIZES_TSHIRT,
        description: "Limited edition means one of a kind — and so are you. Premium ring-spun cotton, built for real bodies that refuse to apologize.",
        description_he: "מהדורה מוגבלת זה אחד ויחיד — בדיוק כמוך. כותנה מסורקת איכותית, נתפר לגוף אמיתי שלא מתנצל.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 2,
        phrase: "More of me to love",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "unisex",
        price: 14,
        image: "images/product-2.jpg",
        colors: ["Black","Cream","Navy"],
        sizes: SIZES_TSHIRT,
        description: "More fabric, more softness, more you. Heavyweight cotton cut generously for the curves that make you, you.",
        description_he: "יותר בד, יותר רכות, יותר אותך. כותנה כבדה בגזרה נדיבה לעקומות שהופכות אותך לך.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 3,
        phrase: "Napping is my cardio",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "unisex",
        price: 28,
        image: "images/product-3.jpg",
        colors: ["Charcoal","Cream","Navy","Forest Green"],
        sizes: SIZES_HOODIE,
        description: "Heavy-fleece hoodie that thinks recovery days are a lifestyle. Cozy enough to sleep in. Sturdy enough to be seen in.",
        description_he: "קפוצון פליז כבד שחושב שימי מנוחה הם סגנון חיים. נעים לישון בו. חזק מספיק להופיע איתו.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 4,
        phrase: "I survived. That's enough.",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "unisex",
        price: 14,
        image: "images/product-4.jpg",
        colors: ["Black","White","Charcoal","Navy"],
        sizes: SIZES_TSHIRT,
        description: "For anyone who made it to today. Soft cotton, honest fit, no medals required — the shirt is the medal.",
        description_he: "לכל מי ששרד עד היום. כותנה רכה, גזרה כנה, בלי צורך במדליה — החולצה היא המדליה.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 5,
        phrase: "Low maintenance, high value",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "unisex",
        price: 14,
        image: "images/product-5.jpg",
        colors: ["Black","White","Cream","Charcoal"],
        sizes: SIZES_TSHIRT,
        description: "Low fuss. Long wear. The tee you reach for when you do not want to think about what to wear.",
        description_he: "מינימום טרחה. מקסימום שימוש. החולצה שאתה מושיט אליה יד כשאתה לא רוצה לחשוב מה ללבוש.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 6,
        phrase: "Not a model. Never wanted to be.",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "unisex",
        price: 28,
        image: "images/product-6.jpg",
        colors: ["Charcoal","Black","Navy"],
        sizes: SIZES_HOODIE,
        description: "Not trying to impress the algorithm. Heavy fleece hoodie built for people who show up, not pose.",
        description_he: "לא מנסה להרשים את האלגוריתם. קפוצון פליז כבד לאנשים שמופיעים, לא מצטלמים.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 15,
        phrase: "Fashion? I prefer comfort.",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "unisex",
        price: 28,
        image: "images/product-15.jpg",
        colors: ["Black","White","Navy","Charcoal"],
        sizes: SIZES_HOODIE,
        description: "Ditch the trends and embrace the only thing that truly matters: absolute comfort. This isn't just a statement; it's a lifestyle choice for those who value chill over 'chic'.",
        description_he: "תזרקו את הטרנדים ותאמצו את הדבר היחיד שבאמת חשוב: נוחות מוחלטת. זה לא רק סלוגן, זו בחירת סגנון חיים למי שמעדיף רוגע על 'שיק'.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 16,
        phrase: "My goal: minimal EXISTENCE.",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "unisex",
        price: 28,
        image: "images/product-16.jpg",
        colors: ["Black","White","Navy","Charcoal"],
        sizes: SIZES_HOODIE,
        description: "Why strive for greatness when you can perfect the art of simply being? This one's for the masters of low-effort living, who've truly embraced their inner couch potato.",
        description_he: "למה להתאמץ כשאפשר לשלוט באמנות של פשוט להיות? הקפוצ'ון הזה מיועד לאלופי החיים במינימום מאמץ, אלה שחיבקו באהבה את תפוחי האדמה הפנימיים שלהם.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 17,
        phrase: "Experienced in EXHAUSTION.",
        type: "ziphoodie",
        typeLabel: "Zip Hoodie",
        gender: "unisex",
        price: 38,
        image: "images/product-17.jpg",
        colors: ["Black","White","Navy","Charcoal"],
        sizes: SIZES_HOODIE,
        description: "Years of 'adulting' have led to this moment: a deep, profound understanding of being utterly worn out. Wear your wisdom proudly, because true experience is truly tiring.",
        description_he: "שנים של 'להיות מבוגר' הובילו לרגע הזה: הבנה עמוקה ונפלאה של להיות גמור לחלוטין. לבשו את החכמה שלכם בגאווה, כי ניסיון אמיתי הוא פשוט מתיש.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 18,
        phrase: "Unfashionably COMFORTABLE.",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "unisex",
        price: 14,
        image: "images/product-18.jpg",
        colors: ["Black","White","Navy","Charcoal"],
        sizes: SIZES_TSHIRT,
        description: "Forget the runway, embrace the real way. This slogan is for anyone whose style mantra is 'if it's not cozy, it's not happening.' Live your best, unfashionably comfortable life.",
        description_he: "שכחו מהמסלול, אמצו את הדרך האמיתית. הסלוגן הזה מיועד לכל מי שמוטו הסטייל שלו הוא 'אם זה לא נוח, זה לא קורה.' תחיו את החיים הכי טובים שלכם, לא אופנתיים אבל נוחים בטירוף.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },

    // ─── MEN'S ─────────────────────

    {
        id: 8,
        phrase: "Born to nap, forced to work",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "men",
        price: 14,
        image: "images/product-8.jpg",
        colors: ["Black","Charcoal","Navy","Red","Forest Green"],
        sizes: SIZES_TSHIRT,
        description: "Soft ring-spun cotton tee for the professionally horizontal. Because the grind is optional but the nap is sacred.",
        description_he: "חולצת כותנה רכה לתנומנים מקצועיים. כי העבודה אופציונלית אבל השינה קדושה.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 9,
        phrase: "Certified overthinker",
        type: "ziphoodie",
        typeLabel: "Zip Hoodie",
        gender: "men",
        price: 32,
        image: "images/product-9.jpg",
        colors: ["Black","Navy","Charcoal"],
        sizes: SIZES_HOODIE,
        description: "Full-zip hoodie for overthinkers. Built for pacing the kitchen at 2am rewriting that text you should not send.",
        description_he: "קפוצון רוכסן לחושבי יתר. נתפר להתהלך במטבח ב-2 בלילה ולשכתב הודעה שאסור לך לשלוח.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },

    // ─── WOMEN'S ───────────────────

    {
        id: 13,
        phrase: "Zero Motivation Club",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "women",
        price: 28,
        image: "images/product-13.jpg",
        colors: ["Charcoal","Cream","Navy"],
        sizes: SIZES_HOODIE,
        description: "Heavy fleece hoodie for charter members of the Zero Motivation Club. Dues paid in naps.",
        description_he: "קפוצון פליז כבד לחברי מועדון אפס מוטיבציה. דמי חבר משולמים בתנומות.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Women's relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 14,
        phrase: "Emotionally attached to my couch",
        type: "longsleeve",
        typeLabel: "Long-Sleeve",
        gender: "women",
        price: 18,
        image: "images/product-14.jpg",
        colors: ["Cream","White","Black","Navy"],
        sizes: SIZES_LONGSLEEVE,
        description: "Women long-sleeve cotton built for couch-based living. Soft, forgiving, honest about its priorities.",
        description_he: "שרוול ארוך בגזרת נשים לחיי ספה. רך, סלחן, כן לגבי הסדר עדיפויות.",
        fabric: "100% combed ring-spun cotton",
        fit: "Women's fitted cut",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_LONGSLEEVE
    },
];

// ──────────────────────────────────────────────────────────────────────
// DB SYNC (added 2026-05-02) — `dubis_products` table is the source of truth
//
// The hardcoded array above is the **fallback baseline** (last known good).
// On script load we fetch active products from Supabase and replace the
// contents of the `products` array in-place. This way:
//   - stock-monitor's auto-restore (active=true on stock return) takes effect
//     immediately on the customer site without requiring a redeploy
//   - active=false products vanish from the UI without code edits
//   - if DB fetch fails, we silently keep the hardcoded fallback
// ──────────────────────────────────────────────────────────────────────

(function () {
  // Type-derived constants for DB rows (DB only stores clothing_type, not the
  // associated fabric/care/size data — those are brand constants).
  const TYPE_INFO = {
    tshirt: {
      typeLabel: 'T-Shirt', sizes: SIZES_TSHIRT, sizeGuide: SIZE_GUIDE_TSHIRT,
      fabric: '100% combed ring-spun cotton', fit: 'Unisex, regular fit',
      printMethod: 'DTG — Direct-to-Garment', printAreas: ['Front', 'Back'],
      care: CARE_TSHIRT, care_he: CARE_TSHIRT_HE,
    },
    hoodie: {
      typeLabel: 'Hoodie', sizes: SIZES_HOODIE, sizeGuide: SIZE_GUIDE_HOODIE,
      fabric: '80% cotton, 20% polyester — heavyweight fleece', fit: 'Unisex, relaxed fit',
      printMethod: 'DTG — Direct-to-Garment', printAreas: ['Front', 'Back'],
      care: CARE_HOODIE, care_he: CARE_HOODIE_HE,
    },
    ziphoodie: {
      typeLabel: 'Zip Hoodie', sizes: SIZES_HOODIE, sizeGuide: SIZE_GUIDE_HOODIE,
      fabric: '80% cotton, 20% polyester — heavyweight fleece', fit: 'Unisex, regular fit',
      printMethod: 'DTG — Direct-to-Garment', printAreas: ['Front', 'Back'],
      care: CARE_HOODIE, care_he: CARE_HOODIE_HE,
    },
    longsleeve: {
      typeLabel: 'Long-Sleeve', sizes: SIZES_LONGSLEEVE, sizeGuide: SIZE_GUIDE_LONGSLEEVE,
      fabric: '100% combed ring-spun cotton', fit: 'Unisex, regular fit',
      printMethod: 'DTG — Direct-to-Garment', printAreas: ['Front', 'Back'],
      care: CARE_TSHIRT, care_he: CARE_TSHIRT_HE,
    },
    cap: {
      typeLabel: 'Cap', sizes: SIZES_CAP,
      sizeGuide: [{ size: 'One Size', note: 'Adjustable strap, fits most head sizes' }],
      fabric: '100% chino cotton twill, unstructured', fit: 'One Size, adjustable strap',
      printMethod: 'Embroidery', printAreas: ['Front'],
      care: ['Spot clean only', 'Do not machine wash', 'Do not tumble dry', 'Reshape and air dry'],
      care_he: CARE_CAP_HE,
    },
  };

  function mapDbRow(row) {
    const rawType = String(row.clothing_type || '').trim();
    // 't-shirt' → 'tshirt', 'long-sleeve' → 'longsleeve', 'zip-hoodie' → 'ziphoodie'
    const type = rawType.replace(/-/g, '');
    const info = TYPE_INFO[type];
    if (!info) return null;
    const pid = row.product_id_numeric;
    return {
      id: pid,
      phrase: row.slogan || '',
      type,
      typeLabel: info.typeLabel,
      gender: row.gender || 'unisex',
      price: Number(row.price_usd) || 0,
      image: `images/product-${pid}.jpg`,
      colors: Array.isArray(row.colors) ? row.colors : [],
      sizes: info.sizes,
      description: row.description_en || '',
      description_he: row.description_he || '',
      fabric: info.fabric, fit: info.fit,
      printMethod: info.printMethod, printAreas: info.printAreas,
      care: info.care, care_he: info.care_he,
      sizeGuide: info.sizeGuide,
    };
  }

  async function loadFromDB() {
    const baseUrl = window.DUBIS_SUPABASE_URL || '';
    const key = window.DUBIS_SUPABASE_ANON || '';
    if (!baseUrl || !key) { console.warn('[DUBIS] Supabase config missing, using fallback products'); return false; }
    const headers = { apikey: key, Authorization: 'Bearer ' + key };
    try {
      // Customer site shows products that are BOTH (a) active=true AND (b) have at least one
      // in-stock variant. OOS products keep active=true so they remain visible in admin and
      // auto-return to the site when Gelato stock comes back. Per oren 2026-05-02.
      const [pRes, sRes] = await Promise.all([
        fetch(baseUrl + '/rest/v1/dubis_products?active=eq.true&select=*&order=product_id_numeric.asc', { headers }),
        fetch(baseUrl + '/rest/v1/product_variant_stock?in_stock=eq.true&select=product_id_numeric', { headers }),
      ]);
      if (!pRes.ok) { console.warn('[DUBIS] dubis_products fetch failed', pRes.status); return false; }
      const rows = await pRes.json();
      if (!Array.isArray(rows) || rows.length === 0) { console.warn('[DUBIS] dubis_products empty'); return false; }

      // Build set of product_ids that have ≥1 in-stock variant. If stock fetch fails,
      // fall back to "show everything active=true" rather than hiding the whole catalog.
      let inStockIds = null;
      if (sRes.ok) {
        const stockRows = await sRes.json();
        inStockIds = new Set((stockRows || []).map(r => r.product_id_numeric));
      } else {
        console.warn('[DUBIS] product_variant_stock fetch failed', sRes.status, '— showing all active products');
      }

      const mapped = rows
        .filter(row => inStockIds === null || inStockIds.has(row.product_id_numeric))
        .map(mapDbRow)
        .filter(Boolean);
      if (mapped.length === 0) { console.warn('[DUBIS] no in-stock rows mapped — keeping fallback'); return false; }

      // Replace contents IN-PLACE so other code holding reference to `products` sees the update.
      products.length = 0;
      for (const p of mapped) products.push(p);
      const hidden = rows.length - mapped.length;
      console.log('[DUBIS] catalog from DB:', mapped.length, 'products visible,', hidden, 'OOS hidden');
      // Re-render if main.js already painted with the fallback array.
      if (typeof renderProducts === 'function') {
        try { renderProducts(); } catch (e) { /* page might not be ready */ }
      }
      if (typeof injectProductStructuredData === 'function') {
        try { injectProductStructuredData(); } catch (e) { /* non-critical */ }
      }
      return true;
    } catch (e) {
      console.warn('[DUBIS] dubis_products fetch threw', e.message);
      return false;
    }
  }

  // Expose a Promise so other code (main.js bootstrap) can await it before first render.
  window.dubisProductsReady = loadFromDB();
})();
