// DUBIS - Product Catalog
// Auto-generated by sync-products — DO NOT EDIT MANUALLY
// Last sync: 2026-05-02T14:29:31.754Z
// Collection 01 - For the rest of us

const SIZES_TSHIRT    = ['S', 'M', 'L', 'XL', '2XL', '3XL'];
const SIZES_HOODIE    = ['S', 'M', 'L', 'XL', '2XL', '3XL'];
const SIZES_LONGSLEEVE = ['S', 'M', 'L', 'XL', '2XL', '3XL'];
// Womens brands (Bella+Canvas 6004, Alternative 9906zt, SOLS 02075) cap below
// the unisex range — verified against Gelato catalog 2026-05-15.
const SIZES_TSHIRT_WOMENS     = ['S', 'M', 'L', 'XL', '2XL'];
const SIZES_HOODIE_WOMENS     = ['S', 'M', 'L', 'XL', '2XL'];
const SIZES_LONGSLEEVE_WOMENS = ['S', 'M', 'L', 'XL'];
const SIZES_CAP       = ['One Size'];

const SIZE_GUIDE_TSHIRT = [
    { size: 'S',   chest: 46, length: 70 },
    { size: 'M',   chest: 51, length: 72 },
    { size: 'L',   chest: 56, length: 74 },
    { size: 'XL',  chest: 61, length: 76 },
    { size: '2XL', chest: 66, length: 78 },
    { size: '3XL', chest: 71, length: 80 },
];

const SIZE_GUIDE_HOODIE = [
    { size: 'S',   chest: 56, length: 67 },
    { size: 'M',   chest: 61, length: 70 },
    { size: 'L',   chest: 66, length: 73 },
    { size: 'XL',  chest: 71, length: 76 },
    { size: '2XL', chest: 76, length: 79 },
    { size: '3XL', chest: 81, length: 82 },
];

const SIZE_GUIDE_LONGSLEEVE = SIZE_GUIDE_TSHIRT;

const CARE_TSHIRT = [
    "Machine wash cold, inside out",
    "Tumble dry low heat",
    "Do not bleach",
    "Do not iron directly on print",
    "Do not dry clean"
];

const CARE_HOODIE = [
    "Machine wash cold, inside out",
    "Tumble dry low heat",
    "Do not bleach",
    "Do not iron directly on print",
    "Do not dry clean"
];

const CARE_TSHIRT_HE = [
    "כביסה קרה במכונה, בפנים החוצה",
    "ייבוש בחום נמוך",
    "אין להלבין",
    "אל תגהץ ישירות על ההדפסה",
    "אין לניקוי יבש"
];

const CARE_HOODIE_HE = CARE_TSHIRT_HE;

const CARE_CAP_HE = [
    "ניקוי ידני בלבד",
    "אין כביסה במכונה",
    "אין לייבש במייבש",
    "עצב מחדש וייבש באוויר"
];

const products = [

    // ─── UNISEX ────────────────────

    {
        id: 1,
        phrase: "I'm not fat, I'm a limited edition",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "unisex",
        price: 14,
        image: "images/product-1.jpg",
        colors: ["Black","White","Cream","Navy","Red"],
        sizes: SIZES_TSHIRT,
        description: "Limited edition means one of a kind — and so are you. Premium ring-spun cotton, built for real bodies that refuse to apologize.",
        description_he: "מהדורה מוגבלת זה אחד ויחיד — בדיוק כמוך. כותנה מסורקת איכותית, נתפר לגוף אמיתי שלא מתנצל.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 2,
        phrase: "More of me to love",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "unisex",
        price: 14,
        image: "images/product-2.jpg",
        colors: ["Black","Cream","Navy"],
        sizes: SIZES_TSHIRT,
        description: "More fabric, more softness, more you. Heavyweight cotton cut generously for the curves that make you, you.",
        description_he: "יותר בד, יותר רכות, יותר אותך. כותנה כבדה בגזרה נדיבה לעקומות שהופכות אותך לך.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 3,
        phrase: "Napping is my cardio",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "unisex",
        price: 28,
        image: "images/product-3.jpg",
        colors: ["Charcoal","Cream","Navy","Forest Green"],
        sizes: SIZES_HOODIE,
        description: "Heavy-fleece hoodie that thinks recovery days are a lifestyle. Cozy enough to sleep in. Sturdy enough to be seen in.",
        description_he: "קפוצון פליז כבד שחושב שימי מנוחה הם סגנון חיים. נעים לישון בו. חזק מספיק להופיע איתו.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 4,
        phrase: "I survived. That's enough.",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "unisex",
        price: 14,
        image: "images/product-4.jpg",
        colors: ["Black","White","Charcoal","Navy"],
        sizes: SIZES_TSHIRT,
        description: "For anyone who made it to today. Soft cotton, honest fit, no medals required — the shirt is the medal.",
        description_he: "לכל מי ששרד עד היום. כותנה רכה, גזרה כנה, בלי צורך במדליה — החולצה היא המדליה.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 5,
        phrase: "Low maintenance, high value",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "unisex",
        price: 14,
        image: "images/product-5.jpg",
        colors: ["Black","White","Cream","Charcoal"],
        sizes: SIZES_TSHIRT,
        description: "Low fuss. Long wear. The tee you reach for when you do not want to think about what to wear.",
        description_he: "מינימום טרחה. מקסימום שימוש. החולצה שאתה מושיט אליה יד כשאתה לא רוצה לחשוב מה ללבוש.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 6,
        phrase: "Not a model. Never wanted to be.",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "unisex",
        price: 28,
        image: "images/product-6.jpg",
        colors: ["Charcoal","Black","Navy"],
        sizes: SIZES_HOODIE,
        description: "Not trying to impress the algorithm. Heavy fleece hoodie built for people who show up, not pose.",
        description_he: "לא מנסה להרשים את האלגוריתם. קפוצון פליז כבד לאנשים שמופיעים, לא מצטלמים.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 7,
        phrase: "DUBIS — For the rest of us",
        type: "cap",
        typeLabel: "Cap",
        gender: "unisex",
        price: 14,
        image: "images/product-7.jpg",
        colors: ["Cream","Black","Navy"],
        sizes: SIZES_CAP,
        description: "Embroidered chino cap for the rest of us — the ones not in the ad. Adjustable strap, unstructured crown, zero pretense.",
        description_he: "כובע כותנה רקום בשבילנו — אלה שלא בפרסומת. רצועה מתכווננת, כתר רך, בלי שטויות.",
        fabric: "100% chino cotton twill, unstructured",
        fit: "One Size, adjustable strap",
        printMethod: "Embroidery",
        printAreas: ["Front"],
        care: ["Spot clean only","Do not machine wash","Do not tumble dry","Reshape and air dry"],
        care_he: CARE_CAP_HE,
        sizeGuide: [{ size: 'One Size', note: 'Adjustable strap, fits most head sizes' }]
    },
    {
        id: 15,
        phrase: "Fashion? I prefer comfort.",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "unisex",
        price: 28,
        image: "images/product-15.jpg",
        colors: ["Black","White","Navy","Charcoal"],
        sizes: SIZES_HOODIE,
        description: "Ditch the trends and embrace the only thing that truly matters: absolute comfort. This isn't just a statement; it's a lifestyle choice for those who value chill over 'chic'.",
        description_he: "תזרקו את הטרנדים ותאמצו את הדבר היחיד שבאמת חשוב: נוחות מוחלטת. זה לא רק סלוגן, זו בחירת סגנון חיים למי שמעדיף רוגע על 'שיק'.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 16,
        phrase: "My goal: minimal EXISTENCE.",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "unisex",
        price: 28,
        image: "images/product-16.jpg",
        colors: ["Black","White","Navy","Charcoal"],
        sizes: SIZES_HOODIE,
        description: "Why strive for greatness when you can perfect the art of simply being? This one's for the masters of low-effort living, who've truly embraced their inner couch potato.",
        description_he: "למה להתאמץ כשאפשר לשלוט באמנות של פשוט להיות? הקפוצ'ון הזה מיועד לאלופי החיים במינימום מאמץ, אלה שחיבקו באהבה את תפוחי האדמה הפנימיים שלהם.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 17,
        phrase: "Experienced in EXHAUSTION.",
        type: "ziphoodie",
        typeLabel: "Zip Hoodie",
        gender: "unisex",
        price: 38,
        image: "images/product-17.jpg",
        colors: ["Black","White","Navy","Charcoal"],
        sizes: SIZES_HOODIE,
        description: "Years of 'adulting' have led to this moment: a deep, profound understanding of being utterly worn out. Wear your wisdom proudly, because true experience is truly tiring.",
        description_he: "שנים של 'להיות מבוגר' הובילו לרגע הזה: הבנה עמוקה ונפלאה של להיות גמור לחלוטין. לבשו את החכמה שלכם בגאווה, כי ניסיון אמיתי הוא פשוט מתיש.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 18,
        phrase: "Unfashionably COMFORTABLE.",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "unisex",
        price: 14,
        image: "images/product-18.jpg",
        colors: ["Black","White","Navy","Charcoal"],
        sizes: SIZES_TSHIRT,
        description: "Forget the runway, embrace the real way. This slogan is for anyone whose style mantra is 'if it's not cozy, it's not happening.' Live your best, unfashionably comfortable life.",
        description_he: "שכחו מהמסלול, אמצו את הדרך האמיתית. הסלוגן הזה מיועד לכל מי שמוטו הסטייל שלו הוא 'אם זה לא נוח, זה לא קורה.' תחיו את החיים הכי טובים שלכם, לא אופנתיים אבל נוחים בטירוף.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 19,
        phrase: "Just trying to MAINTAIN.",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "unisex",
        price: 41,
        image: "images/product-19.jpg",
        colors: ["Black","White","Navy","Charcoal"],
        sizes: SIZES_HOODIE,
        description: "Life's a rollercoaster, and you're just trying to keep your coffee upright. This hoodie is for anyone whose daily goal is simply not to spontaneously combust.",
        description_he: "החיים לפעמים מרגישים כמו מרוץ, ואתם רק מנסים להישאר עם הראש מעל המים. חולצה לכל מי שהשאיפה היומית שלו היא פשוט לשרוד בכבוד.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },

    // ─── MEN'S ─────────────────────

    {
        id: 8,
        phrase: "Born to nap, forced to work",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "men",
        price: 14,
        image: "images/product-8.jpg",
        colors: ["Black","Charcoal","Navy","Red","Forest Green"],
        sizes: SIZES_TSHIRT,
        description: "Soft ring-spun cotton tee for the professionally horizontal. Because the grind is optional but the nap is sacred.",
        description_he: "חולצת כותנה רכה לתנומנים מקצועיים. כי העבודה אופציונלית אבל השינה קדושה.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 9,
        phrase: "Certified overthinker",
        type: "ziphoodie",
        typeLabel: "Zip Hoodie",
        gender: "men",
        price: 32,
        image: "images/product-9.jpg",
        colors: ["Black","Navy","Charcoal"],
        sizes: SIZES_HOODIE,
        description: "Full-zip hoodie for overthinkers. Built for pacing the kitchen at 2am rewriting that text you should not send.",
        description_he: "קפוצון רוכסן לחושבי יתר. נתפר להתהלך במטבח ב-2 בלילה ולשכתב הודעה שאסור לך לשלוח.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 10,
        phrase: "Serial napper",
        type: "longsleeve",
        typeLabel: "Long-Sleeve",
        gender: "men",
        price: 17,
        image: "images/product-10.jpg",
        colors: ["Black","Navy","White","Forest Green"],
        sizes: SIZES_LONGSLEEVE,
        description: "Long-sleeve cotton for committed rest enthusiasts. Covers your arms so you can keep them crossed in peace.",
        description_he: "שרוול ארוך לחובבי מנוחה מסורים. מכסה לך את הידיים כדי שתוכל להשאיר אותן שלובות בשקט.",
        fabric: "100% combed ring-spun cotton",
        fit: "Unisex, regular fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_LONGSLEEVE
    },

    // ─── WOMEN'S ───────────────────

    {
        id: 11,
        phrase: "She believed she could, so she took a nap",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "women",
        price: 14,
        image: "images/product-11.jpg",
        colors: ["White","Cream","Black","Navy"],
        sizes: SIZES_TSHIRT_WOMENS,
        description: "Soft cotton tee with a women fit — because rest is also ambition. Nap first, conquer later.",
        description_he: "חולצה רכה בגזרת נשים — כי גם מנוחה היא שאיפה. קודם לנמנם, אחר כך לכבוש.",
        fabric: "100% combed ring-spun cotton",
        fit: "Women's fitted cut",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 12,
        phrase: "I run on coffee and sarcasm",
        type: "tshirt",
        typeLabel: "T-Shirt",
        gender: "women",
        price: 14,
        image: "images/product-12.jpg",
        colors: ["Black","White","Cream","Navy"],
        sizes: SIZES_TSHIRT_WOMENS,
        description: "The shirt that runs on exactly what you run on. Women fit, ring-spun cotton, permission granted.",
        description_he: "החולצה שרצה על בדיוק מה שאת רצה עליו. גזרת נשים, כותנה מסורקת, ההיתר ניתן.",
        fabric: "100% combed ring-spun cotton",
        fit: "Women's fitted cut",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_TSHIRT
    },
    {
        id: 13,
        phrase: "Zero Motivation Club",
        type: "hoodie",
        typeLabel: "Hoodie",
        gender: "women",
        price: 28,
        image: "images/product-13.jpg",
        colors: ["Charcoal","Navy","Black"],
        sizes: SIZES_HOODIE_WOMENS,
        description: "Heavy fleece hoodie for charter members of the Zero Motivation Club. Dues paid in naps.",
        description_he: "קפוצון פליז כבד לחברי מועדון אפס מוטיבציה. דמי חבר משולמים בתנומות.",
        fabric: "80% cotton, 20% polyester — heavyweight fleece",
        fit: "Women's relaxed fit",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_HOODIE,
        care_he: CARE_HOODIE_HE,
        sizeGuide: SIZE_GUIDE_HOODIE
    },
    {
        id: 14,
        phrase: "Emotionally attached to my couch",
        type: "longsleeve",
        typeLabel: "Long-Sleeve",
        gender: "women",
        price: 18,
        image: "images/product-14.jpg",
        colors: ["White","Black","Navy"],
        sizes: SIZES_LONGSLEEVE_WOMENS,
        description: "Women long-sleeve cotton built for couch-based living. Soft, forgiving, honest about its priorities.",
        description_he: "שרוול ארוך בגזרת נשים לחיי ספה. רך, סלחן, כן לגבי הסדר עדיפויות.",
        fabric: "100% combed ring-spun cotton",
        fit: "Women's fitted cut",
        printMethod: "DTG — Direct-to-Garment",
        printAreas: ["Front", "Back"],
        care: CARE_TSHIRT,
        care_he: CARE_TSHIRT_HE,
        sizeGuide: SIZE_GUIDE_LONGSLEEVE
    },
];

// ──────────────────────────────────────────────────────────────────────
// DB SYNC (added 2026-05-02) — `dubis_products` table is the source of truth
//
// The hardcoded array above is the **fallback baseline** (last known good).
// On script load we fetch active products from Supabase and replace the
// contents of the `products` array in-place. Filters out products that have
// zero in-stock variants, so OOS items disappear from the customer site
// without being removed from admin (per oren 2026-05-02).
//
// NOTE: the `sync-products` endpoint in the agents fn rewrites this file
// after approve-product. It strips this block. If you see the loader
// missing, redeploy this commit. Real fix: disable sync-products since
// the DB loader makes it redundant.
// ──────────────────────────────────────────────────────────────────────

(function () {
  const TYPE_INFO = {
    tshirt: {
      typeLabel: 'T-Shirt', sizes: SIZES_TSHIRT, sizeGuide: SIZE_GUIDE_TSHIRT,
      fabric: '100% combed ring-spun cotton', fit: 'Unisex, regular fit',
      printMethod: 'DTG — Direct-to-Garment', printAreas: ['Front', 'Back'],
      care: CARE_TSHIRT, care_he: CARE_TSHIRT_HE,
    },
    hoodie: {
      typeLabel: 'Hoodie', sizes: SIZES_HOODIE, sizeGuide: SIZE_GUIDE_HOODIE,
      fabric: '80% cotton, 20% polyester — heavyweight fleece', fit: 'Unisex, relaxed fit',
      printMethod: 'DTG — Direct-to-Garment', printAreas: ['Front', 'Back'],
      care: CARE_HOODIE, care_he: CARE_HOODIE_HE,
    },
    ziphoodie: {
      typeLabel: 'Zip Hoodie', sizes: SIZES_HOODIE, sizeGuide: SIZE_GUIDE_HOODIE,
      fabric: '80% cotton, 20% polyester — heavyweight fleece', fit: 'Unisex, regular fit',
      printMethod: 'DTG — Direct-to-Garment', printAreas: ['Front', 'Back'],
      care: CARE_HOODIE, care_he: CARE_HOODIE_HE,
    },
    longsleeve: {
      typeLabel: 'Long-Sleeve', sizes: SIZES_LONGSLEEVE, sizeGuide: SIZE_GUIDE_LONGSLEEVE,
      fabric: '100% combed ring-spun cotton', fit: 'Unisex, regular fit',
      printMethod: 'DTG — Direct-to-Garment', printAreas: ['Front', 'Back'],
      care: CARE_TSHIRT, care_he: CARE_TSHIRT_HE,
    },
    cap: {
      typeLabel: 'Cap', sizes: SIZES_CAP,
      sizeGuide: [{ size: 'One Size', note: 'Adjustable strap, fits most head sizes' }],
      fabric: '100% chino cotton twill, unstructured', fit: 'One Size, adjustable strap',
      printMethod: 'Embroidery', printAreas: ['Front'],
      care: ['Spot clean only', 'Do not machine wash', 'Do not tumble dry', 'Reshape and air dry'],
      care_he: CARE_CAP_HE,
    },
  };

  function mapDbRow(row) {
    const rawType = String(row.clothing_type || '').trim();
    const type = rawType.replace(/-/g, '');
    const info = TYPE_INFO[type];
    if (!info) return null;
    const pid = row.product_id_numeric;
    return {
      id: pid,
      phrase: row.slogan || '',
      type,
      typeLabel: info.typeLabel,
      gender: row.gender || 'unisex',
      price: Number(row.price_usd) || 0,
      // Use Storage bucket URL if approve-product set image_url, else local /images/.
      // Newer products (17+) have AI-generated mockups in Storage; older 1-14 are
      // baked into the repo at /images/product-N.jpg.
      image: row.image_url || `images/product-${pid}.jpg`,
      colors: Array.isArray(row.colors) ? row.colors : [],
      sizes: info.sizes,
      description: row.description_en || '',
      description_he: row.description_he || '',
      fabric: info.fabric, fit: info.fit,
      printMethod: info.printMethod, printAreas: info.printAreas,
      care: info.care, care_he: info.care_he,
      sizeGuide: info.sizeGuide,
    };
  }

  async function loadFromDB() {
    const baseUrl = window.DUBIS_SUPABASE_URL || '';
    const key = window.DUBIS_SUPABASE_ANON || '';
    if (!baseUrl || !key) { console.warn('[DUBIS] Supabase config missing'); return false; }
    const headers = { apikey: key, Authorization: 'Bearer ' + key };
    try {
      const [pRes, sRes] = await Promise.all([
        fetch(baseUrl + '/rest/v1/dubis_products?active=eq.true&select=*&order=product_id_numeric.asc', { headers }),
        fetch(baseUrl + '/rest/v1/product_variant_stock?in_stock=eq.true&select=product_id_numeric', { headers }),
      ]);
      if (!pRes.ok) { console.warn('[DUBIS] dubis_products fetch failed', pRes.status); return false; }
      const rows = await pRes.json();
      if (!Array.isArray(rows) || rows.length === 0) { return false; }
      // Build sets of (a) products with stock data at all, (b) products with ≥1 in-stock variant.
      // A newly-approved product has NO stock rows yet (stock-check hasn't run on it). We
      // give those benefit-of-doubt and SHOW them — otherwise oren approves a product and
      // it's invisible until the daily stock-check fires (oren bug 2026-05-02).
      let stockedIds = null, inStockIds = null;
      if (sRes.ok) {
        const stockRows = await sRes.json();
        inStockIds = new Set((stockRows || []).map(r => r.product_id_numeric));
        // Also fetch the full set of products that HAVE any stock row (to detect "no data" case)
        try {
          const allStockRes = await fetch(baseUrl + '/rest/v1/product_variant_stock?select=product_id_numeric', { headers });
          if (allStockRes.ok) {
            const allRows = await allStockRes.json();
            stockedIds = new Set((allRows || []).map(r => r.product_id_numeric));
          }
        } catch (e) { stockedIds = null; }
      }
      const mapped = rows
        .filter(row => {
          // Show product if: (a) no stock fetch at all → show all; (b) no stock data for this
          // product yet → show (newly approved); (c) at least one in_stock variant → show.
          if (inStockIds === null) return true;
          if (stockedIds !== null && !stockedIds.has(row.product_id_numeric)) return true; // never checked yet
          return inStockIds.has(row.product_id_numeric);
        })
        .map(mapDbRow)
        .filter(Boolean);
      if (mapped.length === 0) { return false; }
      products.length = 0;
      for (const p of mapped) products.push(p);
      const hidden = rows.length - mapped.length;
      console.log('[DUBIS] catalog from DB:', mapped.length, 'visible,', hidden, 'OOS hidden');
      if (typeof renderProducts === 'function') { try { renderProducts(); } catch (e) {} }
      if (typeof injectProductStructuredData === 'function') { try { injectProductStructuredData(); } catch (e) {} }
      return true;
    } catch (e) {
      console.warn('[DUBIS] dubis_products fetch threw', e.message);
      return false;
    }
  }

  window.dubisProductsReady = loadFromDB();
})();
