// DUBIS — Page View / Funnel Event Tracker (v2 with internal-traffic filter)
// POST /api/analytics/track
// Body: { path, referrer, event, meta, session_id, is_dev }
// No auth required — rate limited

const crypto = require('crypto');
const { createClient } = require('@supabase/supabase-js');
const rateLimit = require('../_rateLimit');

const BOT_UA = /bot|crawl|spider|slurp|preview|fetch|monitor|wget|curl|axios|python|node-fetch|headless|phantomjs|puppeteer|playwright|googlebot|bingbot|facebookexternalhit|twitterbot|linkedinbot|whatsapp|slackbot|vercel-screenshot/i;
// 2026-09-09: the Branch-2 checkout telemetry (built 25.08) was silently discarded
// because these names were never added here. An unlisted event falls back to 'pageview',
// so a customer focusing the city field was stored as a page view and the funnel looked
// empty. This list is now the FULL set emitted by js/*.js, generated by grepping
// dubisTrack() call sites. If you add a dubisTrack() call, add its name HERE in the
// same commit or the data does not exist.
const ALLOWED_EVENTS = [
    'add_to_cart',
    'cart_email_saved',
    'cart_restore',
    'checkout_contact_continue',
    'checkout_contact_ok',
    'checkout_contact_shown',
    'checkout_field_focus',
    'checkout_open',
    'checkout_start',
    'fbia_banner_dismiss',
    'fbia_banner_shown',
    'fbia_handoff_click',
    'grid_video_play',
    'home_video_play',
    'newsletter_signup',
    'pageview',
    'pdp_video_play',
    'product_view',
    'purchase',
    'remove_from_cart',
    'section_view',
    'wv_checkout_screen_shown',
    'wv_fallback_opened',
    'wv_redirect_error'
];

module.exports = async function handler(req, res) {
    if (req.method !== 'POST') return res.status(405).end();

    if (rateLimit(req, res, { max: 60, windowMs: 60_000 })) return;

    const {
        path, referrer, event, meta, session_id, is_dev,
        utm_source, utm_medium, utm_campaign, utm_content, utm_term,  // 2026-05-06 — attribution
    } = req.body || {};
    if (!path || typeof path !== 'string') return res.status(400).json({ error: 'Missing path' });
    const evt = ALLOWED_EVENTS.includes(event) ? event : 'pageview';

    // Sanitize UTMs — short strings only, prevent abuse via long payloads
    const trim = (v, max) => (typeof v === 'string' && v.trim()) ? v.trim().slice(0, max) : null;
    const utm = {
        utm_source:   trim(utm_source,   80),
        utm_medium:   trim(utm_medium,   80),
        utm_campaign: trim(utm_campaign, 120),
        utm_content:  trim(utm_content,  120),
        utm_term:     trim(utm_term,     120),
    };

    if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
        return res.status(200).json({ ok: false });
    }

    // ── Internal traffic detection ──
    const ua = req.headers['user-agent'] || '';
    const ip = (req.headers['x-forwarded-for'] || '').split(',')[0].trim() ||
               req.headers['x-real-ip'] || req.socket?.remoteAddress || '';
    const ipHash = ip ? crypto.createHash('sha256').update(ip + (process.env.IP_SALT || 'dubis')).digest('hex').slice(0, 16) : null;
    const uaShort = ua.slice(0, 200);
    const isBot = BOT_UA.test(ua);
    const isInternal = is_dev === true || isBot ||
                       path.startsWith('/#access_token=') ||
                       (path === '/admin' || path.startsWith('/admin'));

    const supabase = createClient(
        process.env.SUPABASE_URL,
        process.env.SUPABASE_SERVICE_ROLE_KEY,
        { auth: { autoRefreshToken: false, persistSession: false } }
    );

    await supabase.from('page_views').insert({
        path: String(path).substring(0, 200),
        referrer: referrer ? String(referrer).substring(0, 500) : null,
        event: evt,
        meta: meta && typeof meta === 'object' ? meta : null,
        session_id: session_id ? String(session_id).slice(0, 64) : null,
        ip_hash: ipHash,
        ua_short: uaShort,
        is_internal: isInternal,
        country_code: req.headers['x-vercel-ip-country'] || null,
        utm_source:   utm.utm_source,
        utm_medium:   utm.utm_medium,
        utm_campaign: utm.utm_campaign,
        utm_content:  utm.utm_content,
        utm_term:     utm.utm_term,
    });

    return res.status(200).json({ ok: true, is_internal: isInternal });
};
